### ISSUE TITLE
Open HRMP channel with Moonbeam

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum#317]
This ticket is for the opening a channel from Pendulum with the Moonbeam parachain 

- How to open/accept a channel [guide](https://www.notion.so/satoshipay/23-08-14-HRMP-Channels-33fa5921d34f4fd1b694d8c9a1e822e5)
- How to open a channel with moonbeam  [guide](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/xc-integration/)

Referendum: fast track (4 days)

## Tasks
The steps are described [here](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/xc-integration/#moonriver-moonbeam). 
- [x] Open (or ensure there is) an HRMP channel from your chain to Moonriver/Moonbeam. Optionally, register MOVR/GLMR
- [x] Create [two Moonbeam Community forum posts](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/xc-integration/#forum-templates) with some key information for the XCM integration:
   - An [XCM Disclosure post](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/forum-templates#xcm-disclosure), where you'll provide some disclosures about the project, the code base, and social network channels
   - An [XCM Proposal post](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/forum-templates#xcm-proposals), where you'll provide some technical information about the proposal itself
   - Link to proposals are here and here (**TODO**)
- [x] Create a batch proposal on Moonbeam/Moonriver to:
  - Accept the incoming HRMP channel
  - Propose the opening of an outgoing HRMP channel from Moonriver/Moonbeam
  - Register the asset as an [XC-20 token](https://docs.moonbeam.network/builders/interoperability/xcm/xc20/overview) (if applicable)
Proposals should be done in the General Admin Track from [OpenGov](https://docs.moonbeam.network/learn/features/governance/#opengov). The normal enactment times are as follows:
  - Moonriver - the Decision Period is approximately 14 days and the enactment time is at least 1 day
  - Moonbeam - the Decision Period is approximately 14 days and the enactment time is at least 1 day
 
- [x] Accept the HRMP channel from Moonriver/Moonbeam on the connecting parachain
- [x] Exchange $50 worth of tokens for testing the XCM integration. Please send the tokens to:
```
AccoundId (Encoded): 5E6kHM4zFdH5KEJE3YEzX5QuqoETVKUQadeY8LVmeh2HyHGt
Decoded (32-Bytes):  0x5a071f642798f89d68b050384132eea7b65db483b00dbb05548d3ce472cfef48
```

- [ ] Provide an Ethereum-styled address for MOVR/GLMR
- [x] Test the XCM integration with the provided tokens

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/317?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
> Successful Integration with Moonbase Alpha TestNet through the Alphanet relay chain (one week testing phase)

How do we know it's a one-week testing phase?

By the way @annatekl, if you want to create a new issue for a sub-task of a checklist you can hover over it and click on the 'Convert to Issue' button. This way, it's automatically linked.
<img width="896" alt="image" src="https://github.com/pendulum-chain/pendulum/assets/6690623/50fba87e-683e-4b16-86e3-5211b2db08ed">

**Comment by annatekl** [comment]
@ebma the one week testing I took from our chat conversation with Moonbeam

**Comment by TorstenStueber** [comment]
Preimage submitted and handed to the council to create a proposal.

Preimage Transaction data: 
```
0x330204290001010002140004000000000700f2052a0113000000000700f2052a01000600228e539e383c00d4070000e803000000900100140d010004000100b920
```

Transaction (Preimage) hash: `0x3f3e8e6e65716430ba21dd125d3188beef571a38304a57126b0bbe1f3219c1a0`

**Comment by TorstenStueber** [comment]
@annatekl I think we can close this ticket now.

**Comment by ebma** [comment]
We also need to complete the other steps in the checklist so that the token is listed on some Moonbeam dApp.

**Comment by ebma** [comment]
I'd consider this done as to my understanding the Moonbeam team acknowledged the channel opening and token transfers work both ways.
