### ISSUE TITLE
Integration with Moonbase Alpha TestNet through the Alphanet relay chain

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum#318]
The first step for a Moonbeam XCM integration is to integrate Foucoco with the Moonbase Alpha TestNet through the Alphanet relay chain. Then a Moonriver integration must be completed before proceeding with Moonbeam.

Full guide [Moonbase Alpha XCM Integration Overview ](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/xc-integration/)
 
Integrating with Moonbase Alpha Testnet is a prerequisite to the actual XCM channel with Moonbeam [ticket](https://github.com/pendulum-chain/pendulum/issues/317)

## Tasks

- [x] [Sync a node](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/xc-integration/#sync-a-node) with the Alphanet relay chain
- [x] [Calculate your parachain sovereign account](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/xc-integration/#calculate-and-fund-the-parachain-sovereign-account) on the Alphanet relay chain
Once your node is fully synced, please get in touch with the Moonbeam team on [Telegram](https://t.me/Moonbeam_Official) or [Discord](https://discord.gg/PfpUATX), so the team can onboard your parachain to the relay chain. Provide the following information for onboarding:
   - The WASM/Genesis head hash
   - Your parachain ID
   - Your sovereign account's address. The Moonbeam team will fund your sovereign account at the relay chain level. This step is required to be able to create the HRMP channel
   - The encoded call data to open an HRMP channel to your parachain, accept the incoming HRMP channel, and [register the assets](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/assets#register-xc-20s) (if applicable). This will be executed through sudo
- [x] Open an HRMP channel to Moonbase Alpha from your parachain (through sudo or via governance)
- [x] Accept the HRMP channel from Moonbase Alpha (through sudo or via governance)
   - The proposal was submitted in [this](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonbase-rpc.dwellir.com#/explorer/query/0x0934ff7b45868ae578bea8691998175dcbde1552c1b7cac72f1475b07c11f6b5) block and is now to be decided
- [x] #366
- [x] For testing the XCM integration, please send some tokens to:
```
AccoundId (Encoded): 5GWpSdqkkKGZmdKQ9nkSF7TmHp6JWt28BMGQNuG4MXtSvq3e
Decoded (32-Bytes):  0xc4db7bcb733e117c0b34ac96354b10d47e84a006b9e7e66a229d174e8ff2a063
```
- [x] Test the XCM integration

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/318?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
@annatekl can you please give more context to this ticket? Why is this required and why do we want this? 
Looking at [this](https://github.com/pendulum-chain/pendulum/issues/317) ticket, it seems like first integrating with Moonbase Alpha Testnet is a prerequisite to the actual XCM channel with Moonbeam. But this does not become clear looking at this ticket alone. I'd appreciate some link to the other ticket in the description so that people reading just this ticket have a chance to understand what it is about.

**Comment by annatekl** [comment]
@ebma added in the description, Moonbeam aksed for a Testnet integration as they want to test the entire flow including adding the token to their dApp

**Comment by ebma** [comment]
@zoveress I need your help to accomplish [this](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/xc-integration/#sync-a-node) step. We need to sync a new node for Foucoco but this time not connecting to Rococo as the relay chain but to another relay chain custom to Moonbeam.

I already compiled the new chain spec that we need. We need these two files to run the node:
[raw-parachain-chainspec.json](https://github.com/pendulum-chain/pendulum/files/12935420/raw-parachain-chainspec.json)
[westend-alphanet-raw-specs.json](https://github.com/pendulum-chain/pendulum/files/12935437/westend-alphanet-raw-specs.json)

What you need to do is to setup a new server and:
- clone the latest `main` branch of the pendulum repository 
- run `cargo build --release -p pendulum-node`
- then run the compiled binary with 
```
./target/release/pendulum-node \
--alice \
--collator \
--force-authoring \
--chain ./raw-parachain-chainspec.json \
--base-path /tmp/parachain/alice \
--port 40333 \
--rpc-port 8844 \
-- \
--execution wasm \
--chain ./westend-alphanet-raw-specs.json \
--port 30343 \
--rpc-port 9977
```

This should make the node start syncing with the relay chain. Let me know if you encounter any issues with this. The steps I describe in this comment are very similar to the steps that we used to run our existing Foucoco collator nodes. Basically the only things that are different are the two chainspec files. So maybe you can also re-use one of the existing pipelines to spin up this other server, not sure.

**Comment by zoveress** [comment]
The new node has been added and it is now syncing.

**Comment by annatekl** [comment]
@ebma is the sync done?

**Comment by ebma** [comment]
Not yet, we are currently at step 3 of [this](https://docs.moonbeam.network/builders/interoperability/xcm/xc-registration/xc-integration/#moonbase-alpha-xcm) list.

**Comment by TorstenStueber** [comment]
@ebma @annatekl I assume that we can close this ticket now?

**Comment by ebma** [comment]
Not yet, we still need to complete the checklist. Currently blocked by [this](https://github.com/pendulum-chain/pendulum/pull/372).

**Comment by ebma** [comment]
This can also be considered done as the Moonbeam team confirmed that token transfers work from Moonbase Alpha to our Moonbeam Foucoco network.
