### ISSUE TITLE
Collator Node Redeployment Tracking for Spacewalk Dependency Update

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum#328]
This ticket is established to monitor and manage the collator node redeployment process in response to the recent Spacewalk dependency update made in #323 

Requirements:
- [ ] successful deployment of the updated code on collator nodes.
- [ ] Confirm that the new changes in the node client code have taken effect.
- [ ] Ensure that the collator nodes are functioning as expected after the redeployment.
- [ ] Perform any necessary testing to verify the integrity of the updated dependencies.

**Comment by TorstenStueber** [comment]
@annatekl what is the status of this ticket? Move to Ready or Icebox?

**Comment by vadaynujra** [comment]
@TorstenStueber @ebma since this seems like a tech ticket, can you share the priority for this, now that Spacewalk is live on Pendulum? We can then decide the answer to Torsten's question above.

**Comment by TorstenStueber** [comment]
Reading this and the linked ticket now indicates that this is obsolete. Let's close when @ebma confirms that this is true.

**Comment by ebma** [comment]
Yes I also think this is obsolete. Seems like this was created as a follow-up to the mention of a required node redeployment in [this](https://github.com/pendulum-chain/pendulum/pull/323) PR. While the description of this ticket is good, I think in the future we don't need tickets like this anymore because the redeployment would be tracked in change request tickets. 

Closing this as completed since the redeployment already happened.
