### ISSUE TITLE
Bump spec_version for Foucoco to 20 and deploy new runtime upgrade

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#495]
## Context 

We want to deploy and test the latest changes introduced by #489 on Foucoco.

## TODO

- [x] Bump spec version to 20. Update: This was actually not necessary. The spec version was already bumped in #489. 
- [x] Compile wasm runtime 
- [x] Perform the runtime upgrade on Foucoco

[foucoco_runtime.compact.compressed.wasm.zip](https://github.com/user-attachments/files/17133835/foucoco_runtime.compact.compressed.wasm.zip)

**Comment by ebma** [comment]
The runtime upgrade was enacted today.
